"use strict";
module.exports = {
  // Ten pixel rows become five terminal lines using foreground/background halves.
  art: {
    trex: [
      "        gggggg",
      "       ggggggg",
      "       ggkwggg",
      "       ggggwww",
      "       gggg   ",
      "      gggllgg ",
      "g    ggggll g ",
      "gggggggggll  ",
      "  ggggggll   ",
      "    cc  cc   ",
    ],
    dog: [
      "        ddd   ",
      "       dbbbb  ",
      "       dbkbb  ",
      "       dbbcckk",
      "       dbbcc  ",
      " b   bbbbbc  ",
      " bbbbbbbbbbc ",
      "  bbbbbbbbc  ",
      "   bb   bb   ",
      "   cc   cc   ",
    ],
    duck: [
      "    yyyy    ",
      "   yyyyyy   ",
      "   yykwyy   ",
      "   yyyyoooo ",
      "    yyyy    ",
      " yyyyyyyy   ",
      "yyyyyccyyy  ",
      " yyyccyyy   ",
      "  yyyyyy    ",
      "   oo oo    ",
    ],
    sixseven: [
      " rrrr  yyyyy ",
      "rr  rr     yy",
      "rr         yy",
      "rrrrr     yy ",
      "rr  rr    yy ",
      "rr  rr   yy  ",
      "rr  rr   yy  ",
      " rrrr    yy  ",
      "             ",
      "             ",
    ],
  },
  palette: {
    g: "#8fbc62",
    l: "#d5df9c",
    d: "#826043",
    b: "#d8a66e",
    c: "#f3dbab",
    y: "#f4cc58",
    o: "#e9923c",
    k: "#252932",
    w: "#fff5dd",
    r: "#7bbbe8",
  },
};
