globalThis.PetsSprites = {
  art: {
    dog: [
      "              ddd     ",
      "             ddbbb    ",
      "             dbbbbb   ",
      "            ddbbkbbb  ",
      "            ddbbbbcckk",
      "            ddbbbcccc ",
      "            ddbbbcc   ",
      "   b    bbbbbbbbcc    ",
      "  bb  bbbbbbbbbbbc    ",
      "  bbbbbbbbbbbbbbbcc   ",
      "   bbbdddbbbbbbbbcc   ",
      "    bbdddbbbbbbbcc    ",
      "    bbbb     bbbb     ",
      "    bbbc     bbbc     ",
      "    bb        bb      ",
      "    ccc       ccc     ",
    ],
    trex: [
      "              ggggggg ",
      "             ggggggggg",
      "             gglgggggg",
      "             ggkgggggg",
      "             ggggggggg",
      "             gggwwwww ",
      "             ggg      ",
      "            ggglll    ",
      "           gggglllgg  ",
      "          ggggglll g  ",
      " g       gggggglll    ",
      " gg     ggggggglll    ",
      "  gggggggggggglll     ",
      "   sssssggggggll      ",
      "      gggg ggg        ",
      "      cc    cc        ",
    ],
    duck: [
      "          ",
      "          ",
      "          ",
      "          ",
      "    yyy   ",
      "   yyyyy  ",
      "   ykyyy  ",
      "   yyyyooo",
      "   yyyyy  ",
      "   yycc   ",
      " yyyyyyy  ",
      "yyyyyccyy ",
      " yyycccyy ",
      "  yyyyyy  ",
      "   o  o   ",
      "  oo  oo  ",
    ],
    sixseven: [
      " rrr   yyyyy ",
      "r          y ",
      "r         y  ",
      "rrrr     y   ",
      "r   r   y    ",
      "r   r   y    ",
      " rrr    y    ",
    ],
  },
  palette: {
    g: "#8fbc62",
    l: "#d5df9c",
    d: "#826043",
    b: "#d8a66e",
    c: "#f3dbab",
    y: "#f4cc58",
    o: "#e9923c",
    k: "#252932",
    w: "#fff5dd",
    s: "#587f45",
    r: "#7bbbe8",
    h: "#a5afbf",
  },
};
